- job:
    name: keystoneclient-devstack-functional
    parent: devstack-tox-functional-consumer
    timeout: 4200
    required-projects:
      - openstack/keystone
      - openstack/python-keystoneclient
    vars:
      tox_envlist: functional

- project:
    templates:
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - publish-openstack-docs-pti
      - check-requirements
      - lib-forward-testing
      - lib-forward-testing-python3
      - release-notes-jobs-python3
    check:
      jobs:
        - keystoneclient-devstack-functional:
            voting: false
